# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration
[bump]
features_always_bump_minor = true
breaking_always_bump_major = true

[changelog]
# A Tera template to be rendered as the changelog's header.
# See https://keats.github.io/tera/docs/#introduction
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n

<!-- next-header -->
"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased] - ReleaseDate
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags |trim | upper_first }}
    {%- for commit in commits | unique(attribute="message") %}
        - {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
            {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
            {% if commit.remote.pr_number %} in \
            [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
            {%- endif -%}
    {% endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
    ### New Contributors
{%- endif -%}

{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor %}\n

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}{% raw %}\n{% endraw -%}{% endif %}

"""
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

<!-- next-url -->
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                {{ self::remote_url() }}/compare/{{ release.previous.version }}...v{{ release.version | trim_start_matches(pat="v") }}
        {% endif -%}
    {% else -%}
        [unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
  # Remove issue numbers.
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
  { message = "^[a|A]dd", group = "<!-- 1 -->Added" },
  { message = "^[s|S]upport", group = "<!-- 1 -->Added" },
  { message = "^[r|R]emove", group = "<!-- 2 -->Removed" },
  { message = "^.*: add", group = "<!-- 1 -->Added" },
  { message = "^.*: support", group = "<!-- 1 -->Added" },
  { message = "^[M|m]erge", group = "<!-- 1 -->Added" },
  { message = "^.*: remove", group = "<!-- 2 -->Removed" },
  { message = "^.*: delete", group = "<!-- 2 -->Removed" },
  { message = "^test", group = "<!-- 1 -->:bug: Fixed" },
  { message = "^[F|fix]", group = "<!-- 1 -->:bug: Fixed" },
  { message = "^.*: fix", group = "<!-- 1 -->:bug: Fixed" },
  { message = "^feat*", group = "<!-- 0 -->:rocket: New Features" },
  { message = "^.*!:", group = "<!-- 0 --> 🏗️ Breaking changes" },
  { message = "^[F|f]ix*", group = "<!-- 1 -->:bug: Fixed" },
  { message = "^deps*:", group = "<!-- 2 -->🧪  Dependencies" },
  { message = "^perf*", group = "<!-- 3 -->:zap: Performance" },
  { message = "^refactor", group = "<!-- 3 --> 🏭 Refactor" },
  { message = "^chore*", group = "<!-- 5 -->:gear: Miscellaneous" },
  { message = "^doc", group = "<!-- 4 --> 📝 Documentation" },
  { message = "^style", group = "<!-- 5 -->:art: Styling" },
  { message = "^.*: .*", group = "<!-- 6 --> 🌀 Other", default_scope = "other" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = true
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"
link_parsers = [
  { pattern = "#(\\d+)", href = "https://github.com/tralahm/proconnect-rs/issues/$1" },
  { pattern = "RFC(\\d+)", text = "ietf-rfc$1", href = "https://datatracker.ietf.org/doc/html/rfc$1" },
]

[remote.github]
# GitHub repository owner.
owner = "tralahm"
# GitHub repository name.
repo = "thesportsdb"
